version: '3.8'

services:
  postgresql-bidding-backend:
    container_name: postgresql-bidding-backend
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bidding-backend
    volumes:
#      - ./data/postgres/users:/var/lib/postgresql/data
      - ./init/user-service-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
