version: '3.8'

services:
  mysql-bidding-site:
    image: mysql
    container_name: mysql-bidding-site
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-bidding-site
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
