version: '3.8'

services:
  mysql-bidding-backend:
    container_name: mysql-bidding-backend
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bidding-backend
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - bidding-backend

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - bidding-backend


networks:
  bidding-backend:
    driver: bridge