spring:
  application:
    name: bidding-backend
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/bidding-backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081

jwt:
  secret: smUdq5b8A31eGFpT/6zSTvEWNGZ4rh7pbY/25YS2hkv3nGaylkSRdMkqgZHjskd8